// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvheqjfxslltlfdfaoqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2aGVxamZ4c2xsdGxmZGZhb3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzgyMjQsImV4cCI6MjA1NDM1NDIyNH0.NYlGC3PZ7rjJImbEaz_UzjAvRU6LcDziDVoGwVSiVXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);